POST  http://localhost:3001/register
content-type: application/json

{
    "username": "Eddy",
    "password": "shadow",
    "email": "edwinadjei381@gmail.com",
    "role": "admin"
}


###
GET http://localhost:3001/authenticate


###
DELETE  http://localhost:3001/users/1