POST  http://localhost:3001/addstudent,
content-type: application/json;
{
    "first_name": "Frank",
    "last_name": "Selah",
    "phone": "057567890",
    "student_class": "JHS 1",
    "gender": "Male",
    "address": "Mallam",
    "hometown": "Tsuibleo",
    "dob": "",
    "user": 15
}


###
GET http://localhost:3001/authenticate


###
DELETE  http://localhost:3001/users/1